spring:
  profiles:
    active:
      - default
---
spring:
  application:
    name: microservicecloud-config-dev
  profiles: dev #开发环境
---
spring:
  application:
    name: microservicecloud-config-test
  profiles: test  #测试环境
